### ISSUE TITLE
Front end Failing on Mac os X El Capitan

### ISSUE THREAD

**Issue by fpiergen** [rvep/dev_frontend#1]
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
19 error node v6.5.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error spring-boot-angular2@1.0.0 test: `karma start config/karma.conf.js`
22 error Exit status 1
23 error Failed at the spring-boot-angular2@1.0.0 test script 'karma start config/karma.conf.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the spring-boot-angular2 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     karma start config/karma.conf.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs spring-boot-angular2
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls spring-boot-angular2
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by borysn** [comment]
@fpiergen thanks for letting me know about the issue. Currently don't have a way to test with os x. From my understanding, it should work the same as linux though. Do you have chrome or chromium installed? It's the only browser that karma is configured for atm. If that's not the issue you can post the full karma test log, and I'll try to poke through it.

if you see any glaring errors specific to os x, google around for a fix, fork the repo, make the changes, and submit a pull request to merge.

**Comment by borysn** [comment]
@fpiergen any word on the osx issue?

**Comment by fpiergen** [comment]
I am not going to be able too look at this for a couple of weeks. I will
let you know then. Thanks for response
