### ISSUE TITLE
Error in Webpack 

### ISSUE THREAD

**Issue by joedayz** [rvep/dev_frontend#2]
This is the problem: 

> webpack --config config/webpack.dev.js --progress --profile --color --display-error-details --display-cached

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
- configuration has an unknown property 'debug'. These properties are valid:
  object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
  The 'debug' property was removed in webpack 2.
  Loaders should be updated to allow passing this option via loader options in module.rules.
  Until loaders are updated one can use the LoaderOptionsPlugin to switch loaders into debug mode:
  plugins: {
   new webpack.LoaderOptionsPlugin({
     debug: true
   })
  }
- configuration.module has an unknown property 'preLoaders'. These properties are valid:
  object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
  Options affecting the normal modules (`NormalModuleFactory`).
- configuration.node.global should be a boolean.
- configuration.resolve.extensions[0] should not be empty.

What should I do?

**Comment by borysn** [comment]
@joedayz I just had to lock down the webpack version at 2.1.0-beta.22. Go ahead and pull the update, should be fine now.

Currently working out the configuration for moving to webpack 2.1.0-beta.23-25 with [spring-boot-angular2](https://github.com/borysn/spring-boot-angular2), having some issues between bootstrap-loader and sass-loader. Once sba2 is all figured out, should be a simple transition for this project.
