### ISSUE TITLE
npm run install

### ISSUE THREAD

**Issue by joedayz** [rvep/dev_frontend#3]
Webpack upgrade is ok. 

But it failing in $ npm run start

¿Is a problem with the version of my tools?

D:\Angular2\dev_frontend>npm run start

> spring-boot-angular2@1.0.0 start D:\Angular2\dev_frontend
> npm run server:dev
> 
> spring-boot-angular2@1.0.0 server:dev D:\Angular2\dev_frontend
> webpack-dev-server --config config/webpack.dev.js --port 3000 -d --progress --profile --watch --content-base src/

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:82:10)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\Program Files\nodejs\node.exe" "C:\Users\josediaz\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "server:dev"
npm ERR! node v5.10.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! spring-boot-angular2@1.0.0 server:dev: `webpack-dev-server --config config/webpack.dev.js --port 3000 -d --progress --profile --watch --content-base src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spring-boot-angular2@1.0.0 server:dev script 'webpack-dev-server --config config/webpack.dev.js --port 3000 -d --progress --profile --watch --content-base src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spring-boot-angular2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config config/webpack.dev.js --port 3000 -d --progress --profile --watch --content-base src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spring-boot-angular2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spring-boot-angular2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Angular2\dev_frontend\npm-debug.log

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\Program Files\nodejs\node.exe" "C:\Users\josediaz\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "start"
npm ERR! node v5.10.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! spring-boot-angular2@1.0.0 start: `npm run server:dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spring-boot-angular2@1.0.0 start script 'npm run server:dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spring-boot-angular2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run server:dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spring-boot-angular2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spring-boot-angular2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Angular2\dev_frontend\npm-debug.log

D:\Angular2\dev_frontend>

**Comment by borysn** [comment]
@joedayz I see that you are testing the application from windows, I actually do not test on windows. Someone else brought the issue to my attention recently. I think this falls back to webpack configuration, and using windows compatible paths for the loaders. I will need some time to investigate.

**Comment by joedayz** [comment]
No problem. I am going to do a review by myself too. I hope my company buy macs in a future for us :P

**Comment by borysn** [comment]
@joedayz hey, the issue is actually not windows compatible paths for the webpack loaders like I thought. I went back through your log, and I missed a line that reads...

`Error: listen EADDRINUSE 127.0.0.1:3000`

It looks like you still have a webpack instance running that is using port 3000, or possibly you have a different application running using that port?

When you exit the application from windows console, try using `CTRL+C` to terminate the batch job.

**Comment by borysn** [comment]
@joedayz also, thought I would mention, I'm not too big of a fan of apple products c(: I use arch or debian (:

**Comment by joedayz** [comment]
@borysn I suppose that :P . No problem. Anything is better than windows. Regards from Perú.

**Comment by borysn** [comment]
@joedayz cheers! Let me know if you run into any more issues.
